services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - authelia-config:/config
    environment:
      - TZ=America/Chicago
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`${AUTHELIA_DOMAIN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls.certresolver=letsencrypt
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      # Authelia middleware
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_DOMAIN}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: authelia-redis
    volumes:
      - authelia-redis:/data
    restart: unless-stopped

volumes:
  authelia-config:
  authelia-redis:

networks:
  default:
    name: dokploy-network
    external: true
