services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - /etc/authelia/configuration.yml:/config/configuration.yml:ro
      - /etc/authelia/users_database.yml:/config/users_database.yml:ro
      - authelia-data:/config
    environment:
      - TZ=America/Chicago
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`${AUTHELIA_DOMAIN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls.certresolver=letsencrypt
      - traefik.http.routers.authelia.service=authelia
      - traefik.http.routers.authelia.middlewares=authelia-ipwhitelist
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      # IP Whitelist middleware - restrict access to admin IPs and Tailscale
      - traefik.http.middlewares.authelia-ipwhitelist.ipwhitelist.sourcerange=${ADMIN_IP_WHITELIST:-100.0.0.0/8,10.0.0.0/16}
      # Authelia forwardauth middleware (for protecting other services)
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_DOMAIN}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: authelia-redis
    volumes:
      - authelia-redis:/data
    restart: unless-stopped

volumes:
  authelia-data:
  authelia-redis:

networks:
  default:
    name: dokploy-network
    external: true
