---
theme: dark
default_2fa_method: "totp"

server:
  address: "tcp://0.0.0.0:9091/"

log:
  level: info

totp:
  issuer: auth.yourdomain.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "auth.yourdomain.com"
      policy: bypass
    - domain: "*.yourdomain.com"
      policy: one_factor

session:
  cookies:
    - domain: yourdomain.com
      authelia_url: https://auth.yourdomain.com
  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    jwt_secret: CHANGE_ME_GENERATE_WITH_OPENSSL_RAND_HEX_32
